### ISSUE TITLE
New Calculations

### ISSUE THREAD

**Issue by Ianhankin** [kalekem/Ising-Model-Simulation#1]
There is a problem with the new graphs, especially in the 1D mat file, which now produces empty graphs. I believe this stems from the fact that due to some recent changes, the dimensions of many of our vectors no longer match up: when I set tempf to 5 some of them are 1x101, and others are 1x51. We need to fix the code so that these match up, otherwise it is impossible to graph. 2D mat is having similar problems, albeit not as severe. Still, we need to know for certain these calculations are correct, and as they are right now, I'm not fully understanding the changes.

**Comment by bbelaineh** [comment]
I see Ian, I changed tempf to have the user enter the temperature desired, but did not change anything else...I'll look back at the 1D mat file and see what's up

**Comment by Ianhankin** [comment]
Okay, I added a bit more, but what I added isn't working all that well yet. The new calculations have kind of broken my best fit lines, but I uploaded what I've got so far anyway.

**Comment by kalekem** [comment]
I think the problem could be on this line of code in I-D mat:    *temp(index) = T*; (line 84).  Matlab is complaining that the variable 'temp' is changing on every loop iteration. And it gives a suggestion that we should preallocate. I can look into that and see if it will resolve the issue

**Comment by kalekem** [comment]
Replaced temp(index) = T; to Temp(index) = T; and the polyfit in I-D graphs seem to work.
